### ISSUE TITLE
Compression ratio

### ISSUE THREAD

**Issue by Iuri-Bertto** [justbetter/magento2-image-optimizer#1]
Its possible change the compression ratio?

I run "run bin/magento justbetter:imageoptimizer:optimizeall", but all the images were left with extremely low quality.

**Comment by rakibabu** [comment]
Hi @Iuri-Bertto ,

Thanks for the feedback, it was already on the roadmap. I'll implement this feature within 2 weeks.

**Comment by rakibabu** [comment]
Hi @Iuri-Bertto ,

Now in version 1.2.0 you can change the compression ratio in de backend in magento 2 and in the CLI. Please check the [readme](https://github.com/justbetter/magento2-image-optimizer) for further details.
