### ISSUE TITLE
mime_content_type() 

### ISSUE THREAD

**Issue by ebofi** [justbetter/magento2-image-optimizer#3]
Fatal error: Uncaught Error: Call to undefined function Spatie\ImageOptimizer\mime_content_type() in /home/adoor/public_html/vendor/spatie/image-optimizer/src/Image.php:22
Stack trace:
#0 /home/adoor/public_html/vendor/spatie/image-optimizer/src/Optimizers/Jpegoptim.php(13): Spatie\ImageOptimizer\Image->mime()
#1 /home/adoor/public_html/vendor/spatie/image-optimizer/src/OptimizerChain.php(83): Spatie\ImageOptimizer\Optimizers\Jpegoptim->canHandle(Object(Spatie\ImageOptimizer\Image))
#2 /home/adoor/public_html/vendor/spatie/image-optimizer/src/OptimizerChain.php(77): Spatie\ImageOptimizer\OptimizerChain->applyOptimizer(Object(Spatie\ImageOptimizer\Optimizers\Jpegoptim), Object(Spatie\ImageOptimizer\Image))
#3 /home/adoor/public_html/vendor/justbetter/magento2-image-optimizer/Console/Command/OptimizeImagesCommand.php(151): Spatie\ImageOptimizer\OptimizerChain->optimize('/home/adoor/pub...')
#4 /home/adoor/public_html/vendor/justbetter/magento2-image-optimizer/Console/Command/OptimizeImagesCommand.php(131): JustBetter\ImageO in /home/adoor/public_html/vendor/spatie/image-optimizer/src/Image.php on line 22
[adoor@conektruae public_html]$ mime_content_type()

**Comment by rakibabu** [comment]
Hi @ebofi ,

Probably you're missing an php extension in your setup. Have a look at this issue in the Spatie ImageOptimizer package: https://github.com/spatie/image-optimizer/issues/76
